cmd_/home/mayur/catkin_ws/src/Udacity-SDC-Radar-Driver-Micro-Challenge/linuxcan/common/softsync.o := gcc -Wp,-MD,/home/mayur/catkin_ws/src/Udacity-SDC-Radar-Driver-Micro-Challenge/linuxcan/common/.softsync.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/4.8/include  -I./arch/x86/include -Iarch/x86/include/generated/uapi -Iarch/x86/include/generated  -Iinclude -I./arch/x86/include/uapi -Iarch/x86/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -Iubuntu/include  -D__KERNEL__ -fno-pie -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -fno-pie -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -maccumulate-outgoing-args -DCONFIG_X86_X32_ABI -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -fno-delete-null-pointer-checks -Wno-maybe-uninitialized -O2 --param=allow-store-data-races=0 -DCC_HAVE_ASM_GOTO -Wframe-larger-than=1024 -fstack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -pg -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -DLINUX=1 -I/home/mayur/catkin_ws/src/Udacity-SDC-Radar-Driver-Micro-Challenge/linuxcan/common/../include -Werror -Wno-date-time -Wall -Wclobbered -Wempty-body -Wignored-qualifiers -Wmissing-parameter-type -Wold-style-declaration -Woverride-init -Wtype-limits -Wuninitialized -Wmissing-field-initializers -D_DEBUG=0 -DDEBUG=0 -DWIN32=0  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(softsync)"  -D"KBUILD_MODNAME=KBUILD_STR(kvcommon)" -c -o /home/mayur/catkin_ws/src/Udacity-SDC-Radar-Driver-Micro-Challenge/linuxcan/common/.tmp_softsync.o /home/mayur/catkin_ws/src/Udacity-SDC-Radar-Driver-Micro-Challenge/linuxcan/common/softsync.c

source_/home/mayur/catkin_ws/src/Udacity-SDC-Radar-Driver-Micro-Challenge/linuxcan/common/softsync.o := /home/mayur/catkin_ws/src/Udacity-SDC-Radar-Driver-Micro-Challenge/linuxcan/common/softsync.c

deps_/home/mayur/catkin_ws/src/Udacity-SDC-Radar-Driver-Micro-Challenge/linuxcan/common/softsync.o := \

/home/mayur/catkin_ws/src/Udacity-SDC-Radar-Driver-Micro-Challenge/linuxcan/common/softsync.o: $(deps_/home/mayur/catkin_ws/src/Udacity-SDC-Radar-Driver-Micro-Challenge/linuxcan/common/softsync.o)

$(deps_/home/mayur/catkin_ws/src/Udacity-SDC-Radar-Driver-Micro-Challenge/linuxcan/common/softsync.o):
