// Generated by gencpp from file kvaser/CANESR.msg
// DO NOT EDIT!


#ifndef KVASER_MESSAGE_CANESR_H
#define KVASER_MESSAGE_CANESR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace kvaser
{
template <class ContainerAllocator>
struct CANESR_
{
  typedef CANESR_<ContainerAllocator> Type;

  CANESR_()
    : header()
    , esrjson()  {
    }
  CANESR_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , esrjson(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _esrjson_type;
  _esrjson_type esrjson;





  typedef boost::shared_ptr< ::kvaser::CANESR_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kvaser::CANESR_<ContainerAllocator> const> ConstPtr;

}; // struct CANESR_

typedef ::kvaser::CANESR_<std::allocator<void> > CANESR;

typedef boost::shared_ptr< ::kvaser::CANESR > CANESRPtr;
typedef boost::shared_ptr< ::kvaser::CANESR const> CANESRConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kvaser::CANESR_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kvaser::CANESR_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kvaser

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'kvaser': ['/home/mayur/ros jade files/catkin_ws/src/Udacity-SDC-Radar-Driver-Micro-Challenge/ros/src/sensing/drivers/can/packages/kvaser/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kvaser::CANESR_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kvaser::CANESR_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kvaser::CANESR_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kvaser::CANESR_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kvaser::CANESR_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kvaser::CANESR_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kvaser::CANESR_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fddc53a50846bc21262a9e34771e8931";
  }

  static const char* value(const ::kvaser::CANESR_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfddc53a50846bc21ULL;
  static const uint64_t static_value2 = 0x262a9e34771e8931ULL;
};

template<class ContainerAllocator>
struct DataType< ::kvaser::CANESR_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kvaser/CANESR";
  }

  static const char* value(const ::kvaser::CANESR_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kvaser::CANESR_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
string esrjson\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::kvaser::CANESR_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kvaser::CANESR_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.esrjson);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CANESR_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kvaser::CANESR_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kvaser::CANESR_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "esrjson: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.esrjson);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KVASER_MESSAGE_CANESR_H
